// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SO.Infra.Database;

#nullable disable

namespace SO.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260111205818_InsertDataInCheckListEntity")]
    partial class InsertDataInCheckListEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListResultEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckListId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOk")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("CheckListResult");
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("HashName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ServiceOrder");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "18b65281-49b6-4b3a-8a2c-71d46b925b18",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 306, DateTimeKind.Local).AddTicks(7217),
                            Email = "alice.smith@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$Q1dslu.6bIpBzwb/O3VfH.djYcG.jTIgv05ZhmKFPf2yMxZHsFe6.",
                            UserName = "alice.smith"
                        },
                        new
                        {
                            Id = "621171c8-8669-4ad3-8a16-360c6edbef17",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 437, DateTimeKind.Local).AddTicks(8803),
                            Email = "bob_johnson@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$A9IajfM0wT8GEdbmYSO3hOyWQ5rgly7RcCwnTZAElFRYNjLhRp2PS",
                            UserName = "bob_johnson"
                        },
                        new
                        {
                            Id = "25f38fb0-cfad-48f6-b01d-da5ba1cb3203",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 567, DateTimeKind.Local).AddTicks(7273),
                            Email = "carol.williams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$kTLOEq6/yZijzL2P7vDI/uveHOuCDQyRLkM8rmlpgXJvOHuIMuXha",
                            UserName = "carol.williams"
                        },
                        new
                        {
                            Id = "a3ecdde6-dbd7-4c27-8b1d-406a62dafa21",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 695, DateTimeKind.Local).AddTicks(5584),
                            Email = "david_brown@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$DcVzr/EAZ6TvPT4wkk7FsOMaHlXTE3idB2EwhOKD6AhbReeveDzKm",
                            UserName = "david_brown"
                        },
                        new
                        {
                            Id = "00589b1e-c677-494f-90f1-e949bacfc8a2",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 825, DateTimeKind.Local).AddTicks(3472),
                            Email = "emily.jones@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$1/vARFhCP9jeqgGxg6bJYunA1Ji4ZuiysmzQTIGGa1YXms72RJC7e",
                            UserName = "emily.jones"
                        },
                        new
                        {
                            Id = "03e9b1e0-1cd2-4eaa-9d59-8bbb96b9eda9",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 15, 953, DateTimeKind.Local).AddTicks(5816),
                            Email = "frank.miller@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$qcWPpc3.RgNtBkm38tU0jeFYmXcyZIJogzcj4.gsV7WOXQ73TMl8e",
                            UserName = "frank_miller"
                        },
                        new
                        {
                            Id = "aaa80d37-767f-4a5e-a0c4-d893b50d28e4",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 82, DateTimeKind.Local).AddTicks(1246),
                            Email = "grace.davis@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$tUg0DNsaOOh65mqxidWuX.5qjlOnPuWSH4r0KgY7nXJx0XIF1cj.m",
                            UserName = "grace.davis"
                        },
                        new
                        {
                            Id = "57344a53-b7da-4429-afbc-ea9441f210e5",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 210, DateTimeKind.Local).AddTicks(5939),
                            Email = "henry_garcia@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$Zxcn765NSZfOpUR51W2pDORFTq9n81uyn7k9xIjXgD/zVKYHbJMxW",
                            UserName = "henry_garcia"
                        },
                        new
                        {
                            Id = "fcf946ed-edc1-45d4-a6a4-a6b0f122584e",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 339, DateTimeKind.Local).AddTicks(4051),
                            Email = "isabella.rodriguez@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$rb4rYHCL3bnYmm5oB2LM4eFQAi3PITp4zCY.QR1CwcjJT2cSaP0wG",
                            UserName = "isabella.rodriguez"
                        },
                        new
                        {
                            Id = "30618d8b-463b-4168-9dba-92b0b5bb3ba6",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 468, DateTimeKind.Local).AddTicks(664),
                            Email = "jack.martin@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$0yoSzt73Xe4aA9q3PQvjtupjMQV4DdQR.SepggOpqFZM9RQCFFfAK",
                            UserName = "jack.martin"
                        },
                        new
                        {
                            Id = "183cd2df-c2c5-4be7-9614-2cafc5222e5f",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 596, DateTimeKind.Local).AddTicks(9913),
                            Email = "karen_lee@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$Wwn/4p29Cn.mqS2zEBv9..p4BEgi14nLDJ1FgkLPOP0i5BA/RYspa",
                            UserName = "karen_lee"
                        },
                        new
                        {
                            Id = "59a5056a-8ddd-4cf3-a697-392434281bdc",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 727, DateTimeKind.Local).AddTicks(4592),
                            Email = "liam.harris@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$1vM2uqvrqQD9UsPCq1SHcuAnYH5yBsk80z4PvhkWpxiKXk2sEcjU.",
                            UserName = "liam.harris"
                        },
                        new
                        {
                            Id = "3363f5e4-4ce8-451f-9849-4ad9d0c54abd",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 863, DateTimeKind.Local).AddTicks(3958),
                            Email = "mia_wilson@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$/VuLdh85eObBacIg60fkSuch6Y2trWMlIsV5irF5Wc2XKb7tf96Oi",
                            UserName = "mia_wilson"
                        },
                        new
                        {
                            Id = "09762cad-ebd2-4fba-9485-c64877ae4a59",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 16, 996, DateTimeKind.Local).AddTicks(752),
                            Email = "noah.clark@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$IQxlApbUft3qzlzcPmahuOzE7NbIM2JgX.0Y.QyP0x8dpc6TuhnY.",
                            UserName = "noah.clark"
                        },
                        new
                        {
                            Id = "869a29f2-3f98-4717-9bb8-50357594895a",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 124, DateTimeKind.Local).AddTicks(3522),
                            Email = "olivia_moore@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$8z/DZgWmlNGp3lnafdtKMufy.AjxISGe7LWTFSHvofwKfk.MDOkjO",
                            UserName = "olivia_moore"
                        },
                        new
                        {
                            Id = "8dfe6be2-f322-4bd4-9624-b5b287df7472",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 252, DateTimeKind.Local).AddTicks(9955),
                            Email = "peter.evans@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$3ldRQmU.I1yRrMiwCqxW.ebtPHJBZL/59VH8CcrOQvObnFNYZvYE6",
                            UserName = "peter.evans"
                        },
                        new
                        {
                            Id = "e7b3fdf5-c212-4740-93b7-10b40b52cb93",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 383, DateTimeKind.Local).AddTicks(3014),
                            Email = "quinn_taylor@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$bq8Z3he9j6YYMZWh5hQGUeuvKFgPohBJ8mE5GbLyHIymPaYfO8kv6",
                            UserName = "quinn_taylor"
                        },
                        new
                        {
                            Id = "142c172e-656f-47f1-a8dd-c1802a9ced7b",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 511, DateTimeKind.Local).AddTicks(6979),
                            Email = "rachel.adams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$T6bHMO1QLTAxQSZ5VVZyyOg4027IIxTVj/xovQTKn12Sdh56LeYAW",
                            UserName = "rachel.adams"
                        },
                        new
                        {
                            Id = "5d5ce925-1cc1-47fa-89e4-638804a813e0",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 640, DateTimeKind.Local).AddTicks(3342),
                            Email = "samuel_king@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$O.T6SkSYC6nHl6Txpvj/meGgCUw5cEowWSvWq64EScGrdEH2YgSA2",
                            UserName = "samuel_king"
                        },
                        new
                        {
                            Id = "585f9d7d-22cf-47e0-9334-7c5658bf9044",
                            CreatedAt = new DateTime(2026, 1, 11, 16, 58, 17, 770, DateTimeKind.Local).AddTicks(3123),
                            Email = "tina.white@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$F67oAplZvtsaRXwfGOMajuv5GQFBk/mcxmSFbctz2xiyw3YSGcZFC",
                            UserName = "tina.white"
                        });
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListResultEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.CheckListEntity", "CheckListEntity")
                        .WithMany("CheckListResults")
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany("CheckListResults")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListEntity");

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany("Images")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.UserEntity", "UserEntity")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Navigation("CheckListResults");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Navigation("CheckListResults");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
