// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SO.Infra.Database;

#nullable disable

namespace SO.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260111210117_InsertDataInCheckListEntity2")]
    partial class InsertDataInCheckListEntity2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CheckList");

                    b.HasData(
                        new
                        {
                            Id = "7597f070-ef1f-4b5e-8fb6-57fc4eec30ee",
                            IsActive = true,
                            Question = "Equipamento liga corretamente"
                        },
                        new
                        {
                            Id = "1ce1b2f4-e6e1-4806-9c89-922e95b9abdb",
                            IsActive = false,
                            Question = "Apresenta danos físicos visíveis"
                        },
                        new
                        {
                            Id = "cecf6d13-871b-453a-b008-74e4ac2cd207",
                            IsActive = true,
                            Question = "Cabos e conexões estão em bom estado"
                        },
                        new
                        {
                            Id = "aaae8562-0eb8-44ce-af4b-392567fbf49e",
                            IsActive = true,
                            Question = "Teste funcional foi realizado após o serviço"
                        },
                        new
                        {
                            Id = "2a7972e8-ec2f-434a-b51c-be7d6dc0606e",
                            IsActive = false,
                            Question = "Cliente recebeu orientações de uso"
                        });
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListResultEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckListId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOk")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("CheckListResult");
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("HashName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ServiceOrder");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "541b4a98-3fe5-4bbb-9ea0-83186d8cce59",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 75, DateTimeKind.Local).AddTicks(9228),
                            Email = "alice.smith@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$wHq4MvtWz6xhGZPrAUXIY.7nUCTY/jycbEt2HBMSXcsbMFXVJBGk2",
                            UserName = "alice.smith"
                        },
                        new
                        {
                            Id = "ca168f0a-fef9-4959-b5d8-9238e5c8a2de",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 212, DateTimeKind.Local).AddTicks(1595),
                            Email = "bob_johnson@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$.DQmkAp.aOJ2yfSmms68yOscYrk9n9rTPof0qBai/YFDeCagP9T6u",
                            UserName = "bob_johnson"
                        },
                        new
                        {
                            Id = "e9aa49df-863d-4287-aa77-d88d1a98c2df",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 343, DateTimeKind.Local).AddTicks(4759),
                            Email = "carol.williams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$eSPh9STq0aDW7IC1OWegHO90Ylm5493qXmwwBmGf5qozIv/cFRJsi",
                            UserName = "carol.williams"
                        },
                        new
                        {
                            Id = "4f0a0726-a12b-48bb-a0a3-7ae442037b58",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 471, DateTimeKind.Local).AddTicks(7286),
                            Email = "david_brown@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$Pie2dwRfYWCdGN.armTwPuP8Mr7//m/1e6u9l9E9ZKK43HtBSwaIW",
                            UserName = "david_brown"
                        },
                        new
                        {
                            Id = "b91b9d4e-b662-416d-b8f2-eba4fa02343b",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 600, DateTimeKind.Local).AddTicks(1384),
                            Email = "emily.jones@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$uPgur8Du2pq7JzFY9jumje/9Am8sO4nSpEO8dzs..RPkaVhwIFpFm",
                            UserName = "emily.jones"
                        },
                        new
                        {
                            Id = "a783ffd0-e771-4060-b200-84f50f371e9e",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 728, DateTimeKind.Local).AddTicks(8251),
                            Email = "frank.miller@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$FNNEWsQncgUNNOJznzJKbeycb8tRIST46u7eia4npdwbYt7I/DVlK",
                            UserName = "frank_miller"
                        },
                        new
                        {
                            Id = "0659da46-c0c0-4bfe-965f-3e17ad11bcb7",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 859, DateTimeKind.Local).AddTicks(9017),
                            Email = "grace.davis@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$s9FaF0Az1r/P19JWy.DBKu8893MuoYXRX/IH1b.sU52n.F9kgUD8O",
                            UserName = "grace.davis"
                        },
                        new
                        {
                            Id = "867c022f-c506-46e1-9507-7975d4c7b13b",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 15, 988, DateTimeKind.Local).AddTicks(9127),
                            Email = "henry_garcia@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$yXXVZKmpGvB0EU2QECPno.DAcuPMIWfpKj5EmIJL9Jv3NeFw/nGQW",
                            UserName = "henry_garcia"
                        },
                        new
                        {
                            Id = "ff643df4-d9bd-4f01-9c91-8e03b6f8f749",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 117, DateTimeKind.Local).AddTicks(8959),
                            Email = "isabella.rodriguez@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$DJIbBQW4luqPN8VUgU3IA.91JVLRb73Grl2HALEJhJvwMYHXxC.2.",
                            UserName = "isabella.rodriguez"
                        },
                        new
                        {
                            Id = "82ca5889-8feb-49de-9fbc-df51b3c4fe21",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 246, DateTimeKind.Local).AddTicks(257),
                            Email = "jack.martin@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$zbCXqfN/DpWHhIKBcdGLHuTgpyH8ZldJPI9pThQOVek270xYm767u",
                            UserName = "jack.martin"
                        },
                        new
                        {
                            Id = "9de2913e-a560-43e9-b8ca-205916cbea7f",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 379, DateTimeKind.Local).AddTicks(4322),
                            Email = "karen_lee@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$KZmlYQTY0rXLM8kO9w2Po.7SvniUqRTvM0KbsdjtVgWd0j8Xfqkwa",
                            UserName = "karen_lee"
                        },
                        new
                        {
                            Id = "0bd0f8a1-c2b0-4e6e-b10e-41c58d0f1797",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 508, DateTimeKind.Local).AddTicks(6015),
                            Email = "liam.harris@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$qLb063/ZNVbLrVVkXVn5wetalCWGXQpDeiQgMRbytN/viPoLp0GBS",
                            UserName = "liam.harris"
                        },
                        new
                        {
                            Id = "67c51451-1a36-450a-b10a-d6ffb62a4f85",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 636, DateTimeKind.Local).AddTicks(5325),
                            Email = "mia_wilson@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$2mGV5eVux8vxJZ8IguOAQu5pOGHSbqB4bdwdAAgSVoN5w5rTepXbe",
                            UserName = "mia_wilson"
                        },
                        new
                        {
                            Id = "9b3ba930-c8d8-4796-9c87-920393880df6",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 764, DateTimeKind.Local).AddTicks(6286),
                            Email = "noah.clark@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$.QliIQvDHAhLgSkK5qfsKeHRuK8YsCUmbIYVnaUsDRuaCDChkHFBG",
                            UserName = "noah.clark"
                        },
                        new
                        {
                            Id = "918d5e65-bd09-4654-a6e0-d8e3c53f5064",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 16, 895, DateTimeKind.Local).AddTicks(3105),
                            Email = "olivia_moore@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$zYs2cMSgKLQ7iE9w/0NDw.VWtqRPY47j.NSDJfa2STgjbUJPujioS",
                            UserName = "olivia_moore"
                        },
                        new
                        {
                            Id = "52bfe38c-26f1-4d88-9d4a-d72679dea98f",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 17, 26, DateTimeKind.Local).AddTicks(3249),
                            Email = "peter.evans@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$G.DyTwpXyThx1AtYdSnJY..VZ9JTrktBotHkdMaIfwqR7D9kyhUbC",
                            UserName = "peter.evans"
                        },
                        new
                        {
                            Id = "b18af8f0-e9a8-4ed1-a0ff-0c83851029d6",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 17, 156, DateTimeKind.Local).AddTicks(9817),
                            Email = "quinn_taylor@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$pY8vHxg3myNvUFXd1PcNP.pNXCtLDvSOnucWGy2MT8L2k2MlT02iK",
                            UserName = "quinn_taylor"
                        },
                        new
                        {
                            Id = "34876b45-0600-49e4-83aa-860af1b66505",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 17, 284, DateTimeKind.Local).AddTicks(9641),
                            Email = "rachel.adams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$fXJlcqjgHJBOKpTutGt2o.C.8yR6.csCX7DgGWT8VIIqbn4BCtfj6",
                            UserName = "rachel.adams"
                        },
                        new
                        {
                            Id = "0e2ac754-7322-48d8-be25-098ed83fce09",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 17, 414, DateTimeKind.Local).AddTicks(6980),
                            Email = "samuel_king@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$1ryCMolagAluuMEmdzOuy.nEPFbTnmJDoDb88vW/fnNGiOfH0vkL.",
                            UserName = "samuel_king"
                        },
                        new
                        {
                            Id = "d3ea82b5-5680-4303-9e39-0f1c3ea77a37",
                            CreatedAt = new DateTime(2026, 1, 11, 17, 1, 17, 542, DateTimeKind.Local).AddTicks(9207),
                            Email = "tina.white@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$XW06DZRcazVd0oBFFUwI2u/uJFiVg7Ws8KBwGSJ3lcaE0.xeV0cd.",
                            UserName = "tina.white"
                        });
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListResultEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.CheckListEntity", "CheckListEntity")
                        .WithMany("CheckListResults")
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany("CheckListResults")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListEntity");

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany("Images")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.UserEntity", "UserEntity")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Navigation("CheckListResults");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Navigation("CheckListResults");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
