// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SO.Infra.Database;

#nullable disable

namespace SO.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("HashName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SO.Domain.Entity.MaintenanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckListId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOk")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ServiceOrder");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "6e4676f0-1f20-44d2-9945-97cc2318d0c3",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 313, DateTimeKind.Local).AddTicks(6067),
                            Email = "alice.smith@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$JdMs5jqZvmaG4Yzze8NRpuGc2Zh1eE0iScoNTFlhIgKh569q6djGa",
                            UserName = "alice.smith"
                        },
                        new
                        {
                            Id = "e29b77ff-6785-4ba6-8717-925f74c5a808",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 442, DateTimeKind.Local).AddTicks(9902),
                            Email = "bob_johnson@example.com",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "$2a$11$HmbrlH7Zz/wBsZ1EWaN8y.XhkDhuStZUQwoSgXxOKS5xp8LwUZnce",
                            UserName = "bob_johnson"
                        },
                        new
                        {
                            Id = "2d5b00f1-ad89-437f-bbba-ee96bb111361",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 571, DateTimeKind.Local).AddTicks(2813),
                            Email = "carol.williams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$MP5EAiiATJ.tTVdZspbkMety7RnE9B2vAG8/0uxdGhCh4jZgS23uG",
                            UserName = "carol.williams"
                        },
                        new
                        {
                            Id = "e32b6ac9-c693-4fdd-997a-13e94dbad440",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 699, DateTimeKind.Local).AddTicks(7437),
                            Email = "david_brown@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$qf8RSRTYylZcgCb/hjQAaOt7IfMRAJlP9FCRgDRWdSKH5NKoLTg.G",
                            UserName = "david_brown"
                        },
                        new
                        {
                            Id = "2434f087-46d1-4ca5-b788-ed0ab20f214a",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 828, DateTimeKind.Local).AddTicks(6454),
                            Email = "emily.jones@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$bWhdPJfUemoywJAywwg9M.G9KNHFTLrxcPQRvMGi7oN1swMvBaYmu",
                            UserName = "emily.jones"
                        },
                        new
                        {
                            Id = "eca786c0-3d92-4abd-8214-cef90c05f5e1",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 21, 959, DateTimeKind.Local).AddTicks(4085),
                            Email = "frank.miller@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$sO3YguQ/fOHCc1G9d.F4ze6dfmbdEEiO8L26t.SDEJrW8isAIUNiK",
                            UserName = "frank_miller"
                        },
                        new
                        {
                            Id = "7bc8c810-2444-4c7a-827d-a4c5372aa3d3",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 93, DateTimeKind.Local).AddTicks(1705),
                            Email = "grace.davis@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$dzt5ffgPNIPkLAR4wBx7ae6AG.10HVDV70gLpbFSuBwX7jMzcujtq",
                            UserName = "grace.davis"
                        },
                        new
                        {
                            Id = "b35f35e4-7bf4-4d6e-a8a7-887e1e69f1fd",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 225, DateTimeKind.Local).AddTicks(9320),
                            Email = "henry_garcia@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$J0DSbLtj5bEIJuTQrkhfueNj3dFHbBovC50WyFTSRAUdT/4atii1S",
                            UserName = "henry_garcia"
                        },
                        new
                        {
                            Id = "b152f611-0a44-4a61-8e1b-914bb963e17d",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 359, DateTimeKind.Local).AddTicks(8265),
                            Email = "isabella.rodriguez@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$Eo4S27.UD4Vp3ZHMrojRYeWRIPP7bi4vKJBwEAcR8HSsiaFdB6GxC",
                            UserName = "isabella.rodriguez"
                        },
                        new
                        {
                            Id = "66eff188-9919-4c94-9734-4334b2d4b9ef",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 505, DateTimeKind.Local).AddTicks(2136),
                            Email = "jack.martin@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$t4F7HJTbj9jtpgCr0xlfJua0XNJFtKqKfWM0m3xmJdkZ.IG3YWlkC",
                            UserName = "jack.martin"
                        },
                        new
                        {
                            Id = "250d2cb7-c3a6-4ec8-beca-5199a9e4d1f1",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 640, DateTimeKind.Local).AddTicks(32),
                            Email = "karen_lee@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$EFgkYV1IMEYcl8V0jtqFgeHQVYbZRVKDxjLMN02kwoc/NNJq1QWGG",
                            UserName = "karen_lee"
                        },
                        new
                        {
                            Id = "4c28aeb6-408a-45fd-a461-5b3cc298deea",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 802, DateTimeKind.Local).AddTicks(2264),
                            Email = "liam.harris@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$94bdh.M3IhWSdauBDour/uJt5IK0PLlDf4DC1HlhVF4FBztHvzike",
                            UserName = "liam.harris"
                        },
                        new
                        {
                            Id = "aa4fa48b-e31d-4df5-ab97-3444e0a8fb4e",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 22, 933, DateTimeKind.Local).AddTicks(9975),
                            Email = "mia_wilson@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$lvK8Nowca1XwZTjfxOn72uxJXv0Rp9E1SPLLwH9lXq3mgUhPveMue",
                            UserName = "mia_wilson"
                        },
                        new
                        {
                            Id = "fc5e9f04-fdbe-4fda-9965-d7ccabc80615",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 64, DateTimeKind.Local).AddTicks(3278),
                            Email = "noah.clark@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$Wa0HHgo5jIBGySvqBIdhSehPF4KSddDwR3XdNqAZyIca2wLewn9.2",
                            UserName = "noah.clark"
                        },
                        new
                        {
                            Id = "92c19972-0957-46c5-a070-f062461697d8",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 192, DateTimeKind.Local).AddTicks(4831),
                            Email = "olivia_moore@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$fwi7rrpiGJAMqqHWZQECguB/BB8wJOSnmK8xDbmWQPTCYMXbJkOkm",
                            UserName = "olivia_moore"
                        },
                        new
                        {
                            Id = "d9eaa607-4682-421c-808f-3546d606dded",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 322, DateTimeKind.Local).AddTicks(9209),
                            Email = "peter.evans@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$rVuLd8U9OJAw0WeR0RDZlu4YBLh1yJZF06YuVW8JrJI8I4q.qBsTG",
                            UserName = "peter.evans"
                        },
                        new
                        {
                            Id = "3486858e-005b-4182-8f76-a277d3c953f7",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 452, DateTimeKind.Local).AddTicks(4326),
                            Email = "quinn_taylor@example.com",
                            IsActive = false,
                            IsAdmin = false,
                            Password = "$2a$11$oYnTDTfRLIDufdkp26jreutWIsjeI0suUYShclW9S80kAr.x/PmFm",
                            UserName = "quinn_taylor"
                        },
                        new
                        {
                            Id = "ac9e2655-cc94-4b2c-8dd4-d5f0a9ceea68",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 582, DateTimeKind.Local).AddTicks(5180),
                            Email = "rachel.adams@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$EkI7Xp8P0bMC8y9QGesQDOnMz6v0JzSPxNdwcJTLArqTG87Xhm.fq",
                            UserName = "rachel.adams"
                        },
                        new
                        {
                            Id = "5cae815d-7048-463e-9f3b-32aad7434fc1",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 712, DateTimeKind.Local).AddTicks(685),
                            Email = "samuel_king@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$SjrLC.O4xI5Kw1Kn8mRhJuoJzjgrdrSSaFN1r3K1FAtMTzQ4Hgp4C",
                            UserName = "samuel_king"
                        },
                        new
                        {
                            Id = "d62a8442-b295-48f8-8bb0-95739abb5f8c",
                            CreatedAt = new DateTime(2026, 1, 10, 18, 31, 23, 840, DateTimeKind.Local).AddTicks(980),
                            Email = "tina.white@example.com",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "$2a$11$HPeQFqG0XhlUDRcUNqLsxeOJ8.5ZsGIvH0bDJScktY6Hm68XRGKIi",
                            UserName = "tina.white"
                        });
                });

            modelBuilder.Entity("SO.Domain.Entity.ImageEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.MaintenanceEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.CheckListEntity", "CheckListEntity")
                        .WithMany("Maintenances")
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SO.Domain.Entity.ServiceOrderEntity", "ServiceOrderEntity")
                        .WithMany("Maintenances")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListEntity");

                    b.Navigation("ServiceOrderEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.HasOne("SO.Domain.Entity.UserEntity", "UserEntity")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("SO.Domain.Entity.CheckListEntity", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("SO.Domain.Entity.ServiceOrderEntity", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("SO.Domain.Entity.UserEntity", b =>
                {
                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
